version: '3.8'

services:
  app:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    ports:
      - 4004:4004
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app
    depends_on:
      - db_mysql_startup
      
  db_mysql_startup:
    container_name: mysql_db_startup
    platform: linux/x86_64
    image: mysql:5.7
    ports: 
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DBNAME}"
      # - "MYSQL_ROOT_USER=${MYSQL_USER}"
      # - "MYSQL_DBNAME=${MYSQL_DBNAME}" 
      # - "MYSQL_HOST=${MYSQL_HOST}"
    volumes:
      - mysql_db_startup:/var/lib/mysql
      
volumes:
  mysql_db_startup:
