name: Deploy Startup

on:
  push:
    branches: [ "main" ]

jobs:
  Deploy-to-Staging:
    runs-on: ubuntu-latest

    steps:    
      - name: "Deploy Go Startup"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/
            git clone --branch main https://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@github.com/Yoga-Saputra/go-startup.git
            git pull origin main
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check out code to Build
  #     uses: actions/checkout@v3

  #   - name: Build Code
  #     run: |
  #       go mod tidy
  #       go build -v ./...
      
