name: Deploy Startup

on:
  push:
    branches: [ "main" ]

jobs:
  Deploy-to-Staging:
    runs-on: ubuntu-latest

    steps:    
      - name: "Deploy Go Startup"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/go-startup
            git pull origin main
            rm -rf /var/www/go-startup/startup
            export PATH=$PATH:/usr/local/go/bin
            go build .
            sudo service startup start
            systemctl daemon-reload
      
