name: Deploy Startup

on:
  push:
    branches: [ "main" ]

jobs:
  # Deploy-to-Staging:
  #   runs-on: ubuntu-latest

  #   steps:    
  #     - name: "Deploy Go Startup"
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         password: ${{ secrets.PASSWORD }}
  #         port: ${{ secrets.PORT }}
  #         script: |
  #           cd /var/www/go-startup
  #           git pull origin main
  #           sudo rm -rf startup
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code to Build
      uses: actions/checkout@v3

    - name: Build Code
      run:
        go build -v ./...
      
