name: Deploy Startup

on:
  push:
    branches: [ "main" ]

jobs:
  Deploy-to-Staging:
    runs-on: ubuntu-latest

    steps:    
      - name: "Deploy Go Startup"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/go-startup
            git pull origin main
            sudo rm -rf startup
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        run: go build -v /var/www/go-startup
